### ISSUE TITLE
Discusión - Cuál guía de estilos seguir? 

### ISSUE THREAD

**Issue by acubillo** [FvD/ctec_ml_2019#10]
Hola! 

Revisando un poco la info sobre la Datatón y según lo conversado hoy en clases noté que existe este libro sobre __"Advance R"__ de Hadley Wickham ([link](http://adv-r.had.co.nz/Style.html)). 

En términos generales se ve muy bien, pero al mismo modo el mismo en su introducción dice:

> You’re reading the first edition of Advanced R; for the second edition, the style guide has been replaced by the tidyverse style guide.

Esta nueva versión 2.0 del libro se encuentra en el siguiente [link](https://adv-r.hadley.nz/index.html). 

__Mi pregunta o la discusión que podría generarse es, desde su punto de vista, cuál guía de estilos podría ser mejor? O serían muy similares?__

Por cierto, el libro incluye mucha info valiosa sobre muchos temas relacionados a R 😃.

**Comment by FvD** [comment]
Hice una traduccion de la guia de Hadley en su momento:

http://www.fransvandunne.com/guia-de-estilo-para-r/

Quizas sirve de inspiración para hacer el de este grupo.

**Comment by acubillo** [comment]
Interesante guía! Estoy de acuerdo en todos los puntos. Nada más tengo una duda, la guía dice lo siguiente:

> Usa dos espacios para añadir una sangría a tu código y nunca usa la tecla TAB. Si te encuentras con código que usa una mezcla de espacios y TABs, cámbialo inmediatamente al uso exclusivo de espacios.  

__¿Por qué no usar tabs? ¿Cuál es la ventaja de espacios en lugar de tabs?__

**Comment by FvD** [comment]
@acubillo Te dijera que entre gustos no hay disgustos, pero esto va mas profundo: 

https://www.youtube.com/watch?v=SsoOG6ZeyUI

**Comment by acubillo** [comment]
Jajajajajajaja creería que soy del equipo TAB 😄. Aunque sí estoy de acuerdo que combinar ambos no 🙅‍♂
