### ISSUE TITLE
Discusión - CRISP-DM vs. Team Data Science Process

### ISSUE THREAD

**Issue by acubillo** [FvD/ctec_ml_2019#16]
Buenas, 

Leyendo un poco sobre CRISP-DM me encontré con el siguiente artículo:

[What’s wrong with CRISP-DM, and is there an alternative?](https://jenstirrup.com/2017/07/01/whats-wrong-with-crisp-dm-and-is-there-an-alternative/)

Me pareció interesante el siguiente enunciado:

> The model no longer seems to be actively maintained. At the time of writing, the official site, CRISP-DM.org, is no longer being maintained. Further, the framework itself has not been updated on issues on working with new technologies (...)

Y al mismo tiempo plantean el uso de __"Team Data Science Process"__ de Microsoft. A continuación un artículo introductorio al proceso:

[Introducing the Team Data Science Process from Microsoft](https://blogs.technet.microsoft.com/machinelearning/2016/10/11/introducing-the-team-data-science-process-from-microsoft/)

Y pues no se ve nada mal. __¿Qué le parece? ¿Lo han usado alguna vez en algún proyecto de datos?__

Saludos!

**Comment by FvD** [comment]
recuerdame por favor a llevar esto a discusión en clase hoy!
