### ISSUE TITLE
Duda sobre el uso de la función cor(x, method = "pearson")

### ISSUE THREAD

**Issue by acubillo** [FvD/ctec_ml_2019#2]
Hola! 

Mientras realizaba la tarea de la semana 1 llegué a la sección de **"Tipos de relación"** y me pareció interesante lo siguiente:

> "Existen varios métodos para calcular la correlación, la función 'cor' permite especificar el tipo de método mediante el parámetro 'method'"

Entonces revisando la documentación de R busqué la función **cor** y la info sobre el parámetro **method**

> method  a character string indicating which correlation coefficient (or covariance) is to be computed. One of "pearson" (default), "kendall", or "spearman": can be abbreviated.

Al buscar más info sobre los distintos métodos de coeficiente de correlación y cuál se ajusta mejor para estos datos me parece que Pearson se ajusta mejor. Pero existen algunos supuestos para poder aplicarlo:

<blockquote>
What assumptions does Pearson's correlation make?

There are five assumptions that are made with respect to Pearson's correlation:

* The variables must be either interval or ratio measurements.
* The variables must be approximately normally distributed.
* There is a linear relationship between the two variables.
* Outliers are either kept to a minimum or are removed entirely. 
* There is homoscedasticity of the data.
</blockquote>

Obtenido de: https://statistics.laerd.com/statistical-guides/pearson-correlation-coefficient-statistical-guide.php

Me llama la atención específicamente la parte de **"The variables must be approximately normally distributed"**. Porque si yo grafico cada una de las variables por aparte en un histograma cada una parece una distribución sesgada a la derecha.  

![000084](https://user-images.githubusercontent.com/1932810/61607811-a720ae80-ac0d-11e9-8507-e85c6c3b805d.png)

Al mismo tiempo no se cumple con **"Outliers are either kept to a minimum or are removed entirely."** 

Entonces mi primer pregunta sería, **¿es viable sacar la correlación usando los datos como están aunque no cumplan con ese par de supuestos? ¿o no es necesario cumplir con todos los supuestos y con que exista una relación linear entre ellos es suficiente?** 

Porque yo podría fácilmente convertir los datos usando una función **log** de la siguiente forma:

```r
info_casas_tidy_log <- info_casas_tidy
info_casas_tidy_log$price <- log(info_casas_tidy$price)
info_casas_tidy_log$sqft_living <- log(info_casas_tidy$sqft_living)
```

Y entonces si vuelvo a graficar los datos ahora sí parecen más una distribución normal.

![000096](https://user-images.githubusercontent.com/1932810/61608402-c3bde600-ac0f-11e9-9b73-34330c086bbc.png)

Inclusive, aplicar la función **cor** me devuelve un coeficiente de correlación mayor:

Coeficiente de correlación con los datos originales:

.                    | price               | sqft_living 
------------ | ------------- | ------------- 
price             | 1.0000000    | 0.9586948 
sqft_living    | 0.9586948   | 1.0000000 

Coeficiente de correlación con el log de los datos:

.                    | price               | sqft_living 
------------ | ------------- | ------------- 
price             | 1.0000000    | **0.9617609**
sqft_living    | **0.9617609**    | 1.0000000

Entonces mi segunda pregunta, **¿es válida esta transformación de los datos? ¿No hace falta? ¿O existe una mejor forma?**

Saludos!

**Comment by FvD** [comment]
Gracias por la pregunta y la elaboración detallada del contexto. Me parece una discusión perfecta para tenerla en grupo durante la clase del sábado.

**Comment by FvD** [comment]
¿Quedo claro con la sesión de hoy?

**Comment by acubillo** [comment]
Claro! Al final queda claro que aplicar log del precio/tamaño es una transformación válida para poder utilizar datos mejor distribuidos, y esta transformación aplica en este caso :)

Muchas gracias!!
